name: tweetpng test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - run: pip install poetry
      - run: poetry install
      - run: py.test tests/
